feat(fake/mock): allow pre-programming methods with specific set of args
drashland/rhum pull request #172
Opened 2022-10-21 05:39 UTC by crookse

Closes #171

2022-12-16 19:43 UTC, ebebbington requested changes
just couple minor nitpicky things

2022-12-16 19:43 UTC, ebebbington commented on console/build_esm_lib.ts
> +  const enabled = optionIndex != -1;
```suggestion
  const enabled = optionIndex !== -1;
```

2022-12-16 19:43 UTC, ebebbington commented on console/build_esm_lib.ts
> +  });
```suggestion
  const extractedOption = args.filter(arg => arg.includes(option));
```

2022-12-17 18:42 UTC, Guergeiro approved these changes

2022-12-19 00:51 UTC, crookse commented
:heart: @Guergeiro @ebebbington 

I'm writing the docs now

2022-12-19 10:23 UTC, Guergeiro approved these changes

2022-12-23 22:12 UTC, crookse commented
@Guergeiro @ebebbington , docs are up: https://github.com/drashland/website-v2/pull/193

2023-01-30 00:18 UTC, merged